### ISSUE TITLE
Bad layout on washpost

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdLiPo#20]
site: http://washingtonpost.com/

happens multiple time

<img width="722" alt="image" src="https://user-images.githubusercontent.com/737638/130319416-c2a0f000-7ee8-40a0-b886-1911b9cef209.png">

**Comment by Real-John-Cheung** [comment]
Washington Post puts their ads at fixed locations and then have a script to overwrite the final node (i.e. our generated text) of the sub tree of the element (i.e our replacement) at that position.

Since the DOM element cannot be locked, we might try:
1. have a list of websites that do  similar things, and try to disable that specific script tab
2. revert any changes that has been made to our replacement with mutation observer (I am experimenting with this)

**Comment by Real-John-Cheung** [comment]
I've added a content script that reverts the DOM changes for our replacements in 1ae7501135a8721

I tested on Firefox and Chrome and noted that the loading process was a bit slower, so I put it in a separate file that is only injected for websites that known to have similar behaviors (maybe we can keep a list of all this kind of websites?)

**Comment by dhowe** [comment]
This makes sense -- please add the list of domains for which this content-script should be injected...

**Comment by Real-John-Cheung** [comment]
I found two sites for now
the list:

- www.washingtonpost.com
- www.nytimes.com
- ...

**Comment by dhowe** [comment]
great -- does this have any ramifications for adnauseam ?

**Comment by Real-John-Cheung** [comment]
>  does this have any ramifications for adnauseam ?

hmm I don't think so since adnauseam doesn't need to render anything in the original spots of the ads. The element being inserted by the websites is a little tag writes "ad", this process would not stop adnauseam from collecting and clicking the ads

**Comment by dhowe** [comment]
once you've add the list to the code, you can close this...

**Comment by Real-John-Cheung** [comment]
the list is added in the manifest.json files
will update the list here and also the list in the files if new sites found
