### ISSUE TITLE
Ad extending beyond content to left and right

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdLiPo#21]
![image](https://user-images.githubusercontent.com/737638/130320970-cec5d293-d379-4207-bf0b-c7fba78ab7e0.png)

**Comment by Real-John-Cheung** [comment]
The above case (and similar ones) are caused by the setting of the origin ad container div (the div being caught by UBO filters): it's width is set to 100% of the window width.
Some ads have complex dom tree structure so I guess that's why the UBO filters try to catch the outer ones...
We might need to think about whether we should change that (and if so, how)...

**Comment by dhowe** [comment]
suggestions?

**Comment by Real-John-Cheung** [comment]
I don't think changing the UBO filters is a good idea... it will be hard to maintain.
Maybe we can leave this after the first release... and deal with it in the future (one idea is to make the rectangles and the text responsive (using vw and vh instead of px?), and limit them to the body size)

**Comment by dhowe** [comment]
agreed - another option might be to ignore (don't draw) ads wider than the body width

**Comment by Real-John-Cheung** [comment]
https://github.com/dhowe/AdLiPo/commit/520a241c76746d7bc34b9c1640bca5d8bde2f29d 
this should fix most of this kind of problems
