### ISSUE TITLE
Text Generation

### ISSUE THREAD

**Issue by Real-John-Cheung** [dhowe/AdLiPo#7]
implant the text generation function

- [x] fork it from https://github.com/dhowe/AdLiPoV2
- [x] update with RiTa v2
- [x] fix lay out

**Comment by dhowe** [comment]
1. We want (obviously) to use your new layout function, rather than the previous version which used the canvas

2.  >  can we load Rita via url so we always got the newest version of it?

We can, but I think it is preferable to package it in the extension as a) it will be faster to load, and b) we avoid regression bugs. In each subsequent release of the extension, we can then package the newest rita that exists

**Comment by Real-John-Cheung** [comment]
> We can, but I think it is preferable to package it in the extension as a) it will be faster to load, and b) we avoid regression bugs. In each subsequent release of the extension, we can then package the newest rita that exists

Sure, that makes sense

**Comment by Real-John-Cheung** [comment]
done
